[package]
name = "glow-protocol"
version = "0.1.0"
authors = ["Glow Savings"]
edition = "2018"
description = "Common helpers for Glow protocol"
license = "Apache-2.0"
repository = ""
homepage = "https://joinglow.com"
documentation = "https://docs.joinglow.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw0 = "0.2"
cw20 = "0.2"
cosmwasm-bignumber = "1.0.0"
cosmwasm-std = { version = "0.10.1", features = ["iterator"] }
cosmwasm-storage = { version = "0.10.1", features = ["iterator"] }
terra-cosmwasm = "1.2.2"
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[profile.dev]
overflow-checks = true

[profile.release]
overflow-checks = true
